language: python
matrix:
  include:
    - python: 3.8
      env: TOXENV=py38-dj22
    - python: 3.8
      env: TOXENV=py38-dj32
    - python: 3.8
      env: TOXENV=py38-dj40

install:
  - ./.travis/install

script:
  - ./.travis/run tox
